# Generated by Django 2.0.7 on 2018-07-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('rate', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('sub_total', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255, null=True)),
                ('discount', models.CharField(max_length=255, null=True)),
                ('grandtotal', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.customerModel')),
            ],
        ),
    ]
